version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: immo_db
      POSTGRES_USER: bilallamamra
      POSTGRES_PASSWORD: boukhalfa_1987
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      Django_DATABASE_URL: postgres://bilallamamra:boukhalfa_1987@db-1:5432/immo_db
