# Generated by Django 4.2 on 2023-04-18 20:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255, unique=True)),
                ('complement_adresse', models.CharField(max_length=255, unique=True)),
                ('ville', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Invalid postal code')])),
                ('montant_loyer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depot_garantie', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Appartement',
                'ordering': ['adresse'],
            },
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='nom')),
                ('prenom', models.CharField(max_length=50, unique=True, verbose_name='prenom')),
                ('adresse', models.CharField(max_length=50, unique=True, verbose_name='adresse')),
                ('email', models.EmailField(max_length=30)),
                ('telephone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'verbose_name': 'Locataire',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paiement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('origine_paiement', models.CharField(max_length=50, unique=True)),
                ('appartement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='immo_app.appartement')),
                ('locataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='immo_app.locataire')),
            ],
            options={
                'verbose_name': 'Paiement',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='EtatLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField()),
                ('montant_solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appartement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='immo_app.appartement')),
                ('locataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='immo_app.locataire')),
            ],
            options={
                'verbose_name': 'Etat_lieux',
            },
        ),
        migrations.CreateModel(
            name='ContratLocataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agence', models.CharField(max_length=50, unique=True, verbose_name='agence')),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField()),
                ('duree_contrat', models.DurationField(blank=True, null=True)),
                ('appartement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='immo_app.appartement')),
                ('locataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='immo_app.locataire')),
            ],
            options={
                'verbose_name': 'Contrat_locataire',
                'ordering': ['-duree_contrat'],
            },
        ),
        migrations.AddField(
            model_name='appartement',
            name='locataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='immo_app.locataire'),
        ),
    ]
