# Generated by Django 4.2 on 2023-04-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immo_app', '0002_fraisagence'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
