# Generated by Django 5.0.6 on 2024-06-30 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immo_app', '0003_locataire_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='postal_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Invalid code postale')]),
        ),
    ]
